---
name: Calling Build Workflow 
on: 
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      app_name: "MyAwesomeApp"
      environment: "staging"
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
