---
name: Calling Build Workflow

on:
  push:
    branches:
      - test

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml

    with:
      app_name: "MyAwesomeApp"
      environment: "staging"

    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Print Build Version
        run: |
          echo "Build version is: ${{ needs.build.outputs.build_version }}"
