---
name: greeting

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    name: greet
    steps: 
        - name: Code Checkout
          uses: actions/checkout@v4

        - name: Hello 
          run: echo "Hello from GitHub actions"
