---
name: Job Outputs
on:
  workflow_dispatch:

jobs:
  set-output:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.step1.outputs.date }}
    steps:
      - id: step1
        run: echo "date=$(date)" >> $GITHUB_OUTPUT

  print-output:
    runs-on: ubuntu-latest
    needs: set-output
    steps:
      - name: Printing the Output
        run: echo "${{ needs.set-output.outputs.date }}"
