---
name: Schedule Tasks
on:
  schedule:
    - cron: '30 2 * * 1'
    - cron: '0 */6 * * *'


jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Which Schedule Triggered
        run: echo "${{ github.event.schedule }}"

      - name: ⚡ Quick Health Check
        run: curl -f -s https://google.com
  
