---
name: Secrets
on:
  workflow_dispatch:

jobs: 
  print:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.MY_SECRET_MESSAGE }}
    steps:
      - name: Access Secret
        run: echo "${{ secrets.MY_SECRET_MESSAGE }}"

      - name: Print Environment variable
        run: echo "$SECRET"
