---
name: Lint Shell Scripts

on:
  workflow_dispatch: 

jobs:
  shellcheck:
    name: ShellCheck Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Shell Linter
        uses: azbagheri/shell-linter@v2
        with:
          severity: "warning" # Options: error, warning, info, style
