---
name: Trigger 2
on:
  push:
    branches:
      - main
      
    paths-ignore:
      - '*.md'

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Name 
        run: echo "$GITHUB_HEAD_REF"
