---
name: Triggers
on:
  push:
    branches:
      - main
      - staging
      
    paths:
      - 'static/**'
      - '.github/actions/**'

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Name
        run: echo "${{ github.head_ref }}"
